/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'storyId' : bigint,
  'text' : string,
  'timestamp' : bigint,
}
export type Condition = { 'asd' : null } |
  { 'ocd' : null } |
  { 'parkinson' : null } |
  { 'anxiety' : null } |
  { 'epilepsy' : null } |
  { 'adhd' : null } |
  { 'ptsd' : null } |
  { 'dyslexia' : null } |
  { 'others' : null } |
  { 'autism' : null } |
  { 'bipolar' : null } |
  { 'depression' : null } |
  { 'schizophrenia' : null };
export interface Story {
  'id' : bigint,
  'title' : string,
  'text' : string,
  'timestamp' : bigint,
  'condition' : Condition,
}
export interface Subscriber {
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'getCommentsByStory' : ActorMethod<[bigint], Array<Comment>>,
  'getStories' : ActorMethod<[], Array<Story>>,
  'getStoriesByCondition' : ActorMethod<[Condition], Array<Story>>,
  'getStoryById' : ActorMethod<[bigint], Story>,
  'getStoryCount' : ActorMethod<[], bigint>,
  'getSubscribers' : ActorMethod<[string], Array<Subscriber>>,
  'submitComment' : ActorMethod<[bigint, string], undefined>,
  'submitStory' : ActorMethod<[string, Condition, string], undefined>,
  'subscribe' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];