/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'storyId' : IDL.Nat,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Condition = IDL.Variant({
  'asd' : IDL.Null,
  'ocd' : IDL.Null,
  'parkinson' : IDL.Null,
  'anxiety' : IDL.Null,
  'epilepsy' : IDL.Null,
  'adhd' : IDL.Null,
  'ptsd' : IDL.Null,
  'dyslexia' : IDL.Null,
  'others' : IDL.Null,
  'autism' : IDL.Null,
  'bipolar' : IDL.Null,
  'depression' : IDL.Null,
  'schizophrenia' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'condition' : Condition,
});
export const Subscriber = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getCommentsByStory' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getStoriesByCondition' : IDL.Func([Condition], [IDL.Vec(Story)], ['query']),
  'getStoryById' : IDL.Func([IDL.Nat], [Story], ['query']),
  'getStoryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSubscribers' : IDL.Func([IDL.Text], [IDL.Vec(Subscriber)], ['query']),
  'submitComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'submitStory' : IDL.Func([IDL.Text, Condition, IDL.Text], [], []),
  'subscribe' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'storyId' : IDL.Nat,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Condition = IDL.Variant({
    'asd' : IDL.Null,
    'ocd' : IDL.Null,
    'parkinson' : IDL.Null,
    'anxiety' : IDL.Null,
    'epilepsy' : IDL.Null,
    'adhd' : IDL.Null,
    'ptsd' : IDL.Null,
    'dyslexia' : IDL.Null,
    'others' : IDL.Null,
    'autism' : IDL.Null,
    'bipolar' : IDL.Null,
    'depression' : IDL.Null,
    'schizophrenia' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'condition' : Condition,
  });
  const Subscriber = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getCommentsByStory' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getStoriesByCondition' : IDL.Func(
        [Condition],
        [IDL.Vec(Story)],
        ['query'],
      ),
    'getStoryById' : IDL.Func([IDL.Nat], [Story], ['query']),
    'getStoryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSubscribers' : IDL.Func([IDL.Text], [IDL.Vec(Subscriber)], ['query']),
    'submitComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'submitStory' : IDL.Func([IDL.Text, Condition, IDL.Text], [], []),
    'subscribe' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };