/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Subscriber {
    name: string;
    email: string;
    timestamp: bigint;
}
export interface Comment {
    id: bigint;
    storyId: bigint;
    text: string;
    timestamp: bigint;
}
export interface Story {
    id: bigint;
    title: string;
    text: string;
    timestamp: bigint;
    condition: Condition;
}
export enum Condition {
    asd = "asd",
    ocd = "ocd",
    parkinson = "parkinson",
    anxiety = "anxiety",
    epilepsy = "epilepsy",
    adhd = "adhd",
    ptsd = "ptsd",
    dyslexia = "dyslexia",
    others = "others",
    autism = "autism",
    bipolar = "bipolar",
    depression = "depression",
    schizophrenia = "schizophrenia"
}
export interface backendInterface {
    getCommentsByStory(storyId: bigint): Promise<Array<Comment>>;
    getStories(): Promise<Array<Story>>;
    getStoriesByCondition(condition: Condition): Promise<Array<Story>>;
    getStoryById(id: bigint): Promise<Story>;
    getStoryCount(): Promise<bigint>;
    getSubscribers(password: string): Promise<Array<Subscriber>>;
    submitComment(storyId: bigint, text: string): Promise<void>;
    submitStory(title: string, condition: Condition, text: string): Promise<void>;
    subscribe(name: string, email: string): Promise<void>;
}
import type { Condition as _Condition, Story as _Story } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getCommentsByStory(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsByStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsByStory(arg0);
            return result;
        }
    }
    async getStories(): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStories();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStories();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoriesByCondition(arg0: Condition): Promise<Array<Story>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoriesByCondition(to_candid_Condition_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoriesByCondition(to_candid_Condition_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoryById(arg0: bigint): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryById(arg0);
                return from_candid_Story_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryById(arg0);
            return from_candid_Story_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStoryCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoryCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoryCount();
            return result;
        }
    }
    async getSubscribers(arg0: string): Promise<Array<Subscriber>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscribers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscribers(arg0);
            return result;
        }
    }
    async submitComment(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitComment(arg0, arg1);
            return result;
        }
    }
    async submitStory(arg0: string, arg1: Condition, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitStory(arg0, to_candid_Condition_n6(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitStory(arg0, to_candid_Condition_n6(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async subscribe(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribe(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribe(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Condition_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Condition): Condition {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Story_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Story {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    text: string;
    timestamp: bigint;
    condition: _Condition;
}): {
    id: bigint;
    title: string;
    text: string;
    timestamp: bigint;
    condition: Condition;
} {
    return {
        id: value.id,
        title: value.title,
        text: value.text,
        timestamp: value.timestamp,
        condition: from_candid_Condition_n4(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    asd: null;
} | {
    ocd: null;
} | {
    parkinson: null;
} | {
    anxiety: null;
} | {
    epilepsy: null;
} | {
    adhd: null;
} | {
    ptsd: null;
} | {
    dyslexia: null;
} | {
    others: null;
} | {
    autism: null;
} | {
    bipolar: null;
} | {
    depression: null;
} | {
    schizophrenia: null;
}): Condition {
    return "asd" in value ? Condition.asd : "ocd" in value ? Condition.ocd : "parkinson" in value ? Condition.parkinson : "anxiety" in value ? Condition.anxiety : "epilepsy" in value ? Condition.epilepsy : "adhd" in value ? Condition.adhd : "ptsd" in value ? Condition.ptsd : "dyslexia" in value ? Condition.dyslexia : "others" in value ? Condition.others : "autism" in value ? Condition.autism : "bipolar" in value ? Condition.bipolar : "depression" in value ? Condition.depression : "schizophrenia" in value ? Condition.schizophrenia : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Array<Story> {
    return value.map((x)=>from_candid_Story_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Condition_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): _Condition {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): {
    asd: null;
} | {
    ocd: null;
} | {
    parkinson: null;
} | {
    anxiety: null;
} | {
    epilepsy: null;
} | {
    adhd: null;
} | {
    ptsd: null;
} | {
    dyslexia: null;
} | {
    others: null;
} | {
    autism: null;
} | {
    bipolar: null;
} | {
    depression: null;
} | {
    schizophrenia: null;
} {
    return value == Condition.asd ? {
        asd: null
    } : value == Condition.ocd ? {
        ocd: null
    } : value == Condition.parkinson ? {
        parkinson: null
    } : value == Condition.anxiety ? {
        anxiety: null
    } : value == Condition.epilepsy ? {
        epilepsy: null
    } : value == Condition.adhd ? {
        adhd: null
    } : value == Condition.ptsd ? {
        ptsd: null
    } : value == Condition.dyslexia ? {
        dyslexia: null
    } : value == Condition.others ? {
        others: null
    } : value == Condition.autism ? {
        autism: null
    } : value == Condition.bipolar ? {
        bipolar: null
    } : value == Condition.depression ? {
        depression: null
    } : value == Condition.schizophrenia ? {
        schizophrenia: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
